name: PowerShell script
author: Amadevus
description: >
  Run PowerShell scripts within a hydrated context,
  with workflow-command cmdlets; inspired by actions/github-script.
inputs:
  script:
    description: PowerShell script to execute in Actions-hydrated context
    required: true
outputs:
  result:
    description: Return value of script execution
    value: ${{ steps.script.outputs.result }}
runs:
  using: composite
  steps:
    - run: ${{ github.action_path }}/action.ps1
      id: script
      shell: pwsh
      env:
        PWSH_SCRIPT_ACTION_TEXT: ${{ inputs.script }}
        PWSH_SCRIPT_ACTION_GITHUB: ${{ toJson(github) }}
        PWSH_SCRIPT_ACTION_JOB: ${{ toJson(job) }}
        PWSH_SCRIPT_ACTION_RUNNER: ${{ toJson(runner) }}
        PWSH_SCRIPT_ACTION_STRATEGY: ${{ toJson(strategy) }}
        PWSH_SCRIPT_ACTION_MATRIX: ${{ toJson(matrix) }}
branding:
  icon: terminal
  color: blue
