name: ChatOps
on:
  issue_comment:
    types: [created]
jobs:
  dispatch:
    runs-on: ubuntu-latest
    if: startsWith(github.event.comment.body, '/')
    steps:
      - name: /command dispatch
        uses: peter-evans/slash-command-dispatch@v1
        with:
          token: ${{ secrets.SLASH_COMMAND_DISPATCH_TOKEN }}
          reaction-token: ${{ github.token }}
          config: >
            [
              {
                "command": "tag",
                "permission": "admin",
                "named_args": true
              },
              {
                "command": "demo",
                "permission": "read"
              }
            ]
