name: Tag command
# trigger by chatops '/tag v1.0.0 ref=main force'
# first non-named arg is interpreted as the tag name to be created
# ref defaults to default repo branch and is the ref going to be tagged
# 'force', if specified in args, adds `--force` to tagging operations (to move major tags like v1/v2)
on:
  repository_dispatch:
    types: [tag-command]
jobs:
  tag:
    runs-on: ubuntu-latest
    env:
      tag_name: ${{ github.event.client_payload.slash_command.args.unnamed.arg1 }}
    steps:
      - name: Add run link to command comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          body: "[Workflow run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})"
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.client_payload.slash_command.args.named.ref }}
      - name: Resolve version, tag and push
        uses: ./
        with:
          script: |
            $args = $github.event.client_payload.slash_command.args.unnamed
            $force = ($args.GetEnumerator() | ? Value -eq 'force') ? '--force' : ''
            $tag = $env:tag_name
            if (-not $tag) {
              throw "Can't create empty-named tag. Please specify tag after command: /tag vX.Y.Z"
            }
            git tag $tag $force || $(throw "git tag $tag $force failed.")
            git push origin $tag $force || $(throw "git push origin $tag $force failed.")
      - name: Add tag info and reaction to command comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          body: |
            Pushed tag [`${{ env.tag_name }}`][tag]

            [tag]: https://github.com/${{ github.repository }}/tree/${{ env.tag_name }}
          reactions: hooray
      - name: Add reaction to command comment on failure
        uses: peter-evans/create-or-update-comment@v2
        if: failure()
        with:
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reactions: "-1"
